"""
Event definitions for event-driven backtesting.

Events represent different stages in the backtest lifecycle:
- MarketEvent: New market data (OHLCV bar)
- SignalEvent: Trading signal from strategy
- OrderEvent: Order to be executed
- FillEvent: Completed trade execution
"""

from datetime import datetime
from typing import Dict, Any, Optional
from dataclasses import dataclass, field


@dataclass
class MarketEvent:
    """
    Market data event - represents a new OHLCV bar.

    Attributes:
        timestamp: Bar timestamp
        symbol: Trading pair (e.g., 'BTC/USDT')
        ohlcv: Dict with 'open', 'high', 'low', 'close', 'volume'
        metadata: Optional dict for additional data (e.g., regime classification)
    """
    timestamp: datetime
    symbol: str
    ohlcv: Dict[str, float]
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def open(self) -> float:
        return self.ohlcv['open']

    @property
    def high(self) -> float:
        return self.ohlcv['high']

    @property
    def low(self) -> float:
        return self.ohlcv['low']

    @property
    def close(self) -> float:
        return self.ohlcv['close']

    @property
    def volume(self) -> float:
        return self.ohlcv['volume']


@dataclass
class SignalEvent:
    """
    Signal event - trading signal generated by strategy.

    Attributes:
        timestamp: Signal generation time
        symbol: Trading pair
        signal_type: 'BUY', 'SELL', or 'HOLD'
        strength: Signal strength (0.0 to 1.0, optional)
        metadata: Optional dict for strategy-specific data
    """
    timestamp: datetime
    symbol: str
    signal_type: str  # 'BUY', 'SELL', 'HOLD'
    strength: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class OrderEvent:
    """
    Order event - order to be executed.

    Attributes:
        timestamp: Order creation time
        symbol: Trading pair
        order_type: 'MARKET' or 'LIMIT'
        quantity: Amount to trade
        direction: 'BUY' or 'SELL'
        price: Limit price (None for market orders)
    """
    timestamp: datetime
    symbol: str
    order_type: str  # 'MARKET', 'LIMIT'
    quantity: float
    direction: str  # 'BUY', 'SELL'
    price: Optional[float] = None


@dataclass
class FillEvent:
    """
    Fill event - completed order execution.

    Attributes:
        timestamp: Execution time
        symbol: Trading pair
        quantity: Amount traded
        direction: 'BUY' or 'SELL'
        fill_price: Actual execution price
        commission: Trading fee paid
        slippage: Slippage rate applied
    """
    timestamp: datetime
    symbol: str
    quantity: float
    direction: str  # 'BUY', 'SELL'
    fill_price: float
    commission: float
    slippage: float = 0.0

    @property
    def cost(self) -> float:
        """Calculate total cost of the fill (quantity * price + commission)"""
        return (self.quantity * self.fill_price) + self.commission
